name: test

on:
  push:
    branches:
      - main
      - release-*
    paths:
      - 'docs/tempo/website/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
 
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - uses: actions/checkout@v2
      
      # This writes the destination into $DEST
      - run: |
          go run test.go ${{ github.ref_name }}
     
      - shell: bash
        run: |
          test -n "dest is $DEST"
          test -n "${{ steps.publish.outputs.working_directory }}"