name: test

on:
  push:
    branches:
      - main
      - release-*
    tags:        
      - v[0-9]+.[0-9]+.[0-9]+
    paths:
      - 'docs/tempo/website/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
 
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - uses: actions/checkout@v2
      
      # This writes the destination into $DEST
      - run: |
          cd .github/workflows/
          go run test.go ${{ github.ref_name }}
     
      - shell: bash
        run: |
          echo "dest is $DEST"

      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: "mdisibio/grafana-github-actions"
          path: ./actions
          ref: docstarget

      - name: Install Actions
        run: npm install --production --prefix ./actions

      - id:   target
        name: Get target
        uses: ./actions/docs-target
        with:
          ref_name: ${{ github.ref_name }}

      - shell: bash
        run: |
          echo "action returned " ${{ steps.target.outputs.target }} 